### ISSUE TITLE
How about integrating with uWebsocket is this possible?

### ISSUE THREAD

**Issue by sanchezzzhak** [moleculerjs/moleculer-web#102]
Project https://github.com/uNetworking/uWebSockets.js

**Comment by sanchezzzhak** [comment]
prototype  (Later I will make a repository...)
config/serve.config.js
```
module.exports = {
    driver: "uws",
    port: 3005,
    ip: "127.0.0.1"
};
```
src/components/response-data.js
```js
const DRIVERS = require('../consts/http-drivers');
const IP = require('../helpers/client-ip');

function RequestData(originalRequest, driver) {
  this._request = originalRequest;
  this._driver = driver;
  this._ip = null;
}

RequestData.prototype.getUrl = function() {
  return this.__request.getUrl();
};

RequestData.prototype.getQuery = function() {
  return this.__request.getQuery();
};

/**
 * @param name {String}
 * @returns {*}
 */
RequestData.prototype.getHeader = function(name){
  if(DRIVERS.UWS === this._driver){
    return this._request.getHeader(name);
  }
  
  return this._request.headers[name] ? this._request.headers[name]: null;
};

/**
 * @returns {null|String}
 */
RequestData.prototype.getClientIp = function() {
  if(this._ip === null){
    this._ip = IP.getClientIp(this);
  }
  return this._ip;
};

RequestData.prototype.setClientIp = function(ip) {
  his._ip = ip;
};
module.exports = RequestData;
```
src/components/response-data.js
```js
const DRIVERS = require('../consts/http-drivers');

function ResponseData(originalResponse, driver) {
  this._response = originalResponse;
  this._driver = driver;
}

ResponseData.prototype.end = function(content = null){
  this._response.end(content);
};

ResponseData.prototype.redirect = function(url, code = 302){
  this._response.writeHead(code, {
	"Location": url,
	"Content-Length": "0"
  });
  this.end();
};

module.exports = ResponseData;
```
src/helpers/client-ip.js
```js
const is = require('is_js');

exports.getIpForHeaders = function (req) {
    let items = [] ;
    let rule = /\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/g;
    let ips = JSON.stringify(req.headers).match(rule);
    ips.forEach(function (el) {
        if(is.ip(el)){
            items.push(el);
        }
    });
    return items;
};


exports.getClientIpFromXForwardedFor = function(value) {
    if (!value) {
        return null;
    }
    // x-forwarded-for may return multiple IP addresses in the format:
    // "client IP, proxy 1 IP, proxy 2 IP"
    // Therefore, the right-most IP address is the IP address of the most recent proxy
    // and the left-most IP address is the IP address of the originating client.
    // source: http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html
    // Azure Web App's also adds a port for some reason, so we'll only use the first part (the IP)
    const forwardedIps = value.split(',').map((e) => {
        const ip = e.trim();
        if (ip.includes(':')) {
            const splitted = ip.split(':');
            // make sure we only use this if it's ipv4 (ip:port)
            if (splitted.length === 2) {
                return splitted[0];
            }
        }
        return ip;
    });
    
    // Sometimes IP addresses in this header can be 'unknown' (http://stackoverflow.com/a/11285650).
    // Therefore taking the left-most IP address that is not unknown
    // A Squid configuration directive can also set the value to "unknown" (http://www.squid-cache.org/Doc/config/forwarded_for/)
    return forwardedIps.find(is.ip);
};

/**
 *
 * x-forwarded-for: client, proxy1, proxy2, proxy3
 * **/

/**
 Steps detect
 X-Client-IP
 X-Forwarded-For (Header may return multiple IP addresses in the format: "client IP, proxy 1 IP, proxy 2 IP", so we take the the first one.)
 CF-Connecting-IP (Cloudflare)
 True-Client-Ip (Akamai and Cloudflare)
 X-Real-IP (Nginx proxy/FastCGI)
 X-Cluster-Client-IP (Rackspace LB, Riverbed Stingray)
 X-Forwarded, Forwarded-For and Forwarded (Variations of #2)
 req.connection.remoteAddress
 req.socket.remoteAddress
 req.connection.socket.remoteAddress
 req.info.remoteAddress
 * @param req
 * @returns {String}
 */
exports.getClientIp = function(req) {
    // Standard headers used by Amazon EC2, Heroku, and others.
    if (is.ip(req.getHeader('x-client-ip'))) {
        return req.getHeader('x-client-ip');
    }
    
    // Load-balancers (AWS ELB) or proxies.
    const xForwardedFor = this.getClientIpFromXForwardedFor(req.getHeader('x-forwarded-for'));
    if (is.ip(xForwardedFor)) {
        return xForwardedFor;
    }
    
    // Cloudflare.
    // @see https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-
    // CF-Connecting-IP - applied to every request to the origin.
    if (is.ip(req.getHeader('cf-connecting-ip'))) {
        return req.getHeader('cf-connecting-ip');
    }
    
    // Akamai and Cloudflare: True-Client-IP.
    if (is.ip(req.getHeader('true-client-ip'))) {
        return req.getHeader('true-client-ip');
    }
    
    // Default nginx proxy/fcgi; alternative to x-forwarded-for, used by some proxies.
    if (is.ip(req.getHeader('x-real-ip'))) {
        return req.getHeader('x-real-ip');
    }
    
    // (Rackspace LB and Riverbed's Stingray)
    // http://www.rackspace.com/knowledge_center/article/controlling-access-to-linux-cloud-sites-based-on-the-client-ip-address
    // https://splash.riverbed.com/docs/DOC-1926
    if (is.ip(req.getHeader('x-cluster-client-ip'))) {
        return req.getHeader('x-cluster-client-ip');
    }
    
    if (is.ip(req.getHeader('x-forwarded'))) {
        return req.getHeader('x-forwarded');
    }
    
    if (is.ip(req.getHeader('forwarded-for'))) {
        return req.getHeader('forwarded-for');
    }
    
    if (is.ip(req.getHeader('forwarded'))) {
        return req.getHeader('forwarded');
    }
    
    // // Remote address checks.
    // if (is.existy(req.connection)) {
    //     if (is.ip(req.connection.remoteAddress)) {
    //         return req.connection.remoteAddress;
    //     }
    //     if (is.existy(req.connection.socket) && is.ip(req.connection.socket.remoteAddress)) {
    //         return req.connection.socket.remoteAddress;
    //     }
    // }
    //
    // if (is.existy(req.socket) && is.ip(req.socket.remoteAddress)) {
    //     return req.socket.remoteAddress;
    // }
    //
    // if (is.existy(req.info) && is.ip(req.info.remoteAddress)) {
    //     return req.info.remoteAddress;
    // }
    
    return '0.0.0.0';
};

```


src/mixins/web-server.js
```js
const Http = require('http');
const Uws = require('uWebSockets.js');

const ResponseData = require('../components/response-data');
const RequestData = require('../components/request-data');

const DRIVERS = require('../consts/http-drivers');

const config = require('../../config/server.config');

module.exports = {
  name: 'web-server',
  actions: {
	rest: {
	  visibility: "private",
	  async handler(ctx) {
		const req = ctx.params.req;
		const res = ctx.params.res;
		
		
		if (!this.routes || this.routes.length === 0) {
		  return null;
		}
		
		for (let i = 0, l = this.routes.length; i < l; i++) {
		  const route = this.routes[i];
		  let url = req.getUrl();
		  if (url.startsWith(route.path)) {
			return this.routeHandler(ctx, route, req, res);
		  }
		}
		
		return null;
	  }
	}
  },
  settings: {
	driver: config.driver,
	port: config.port,
	ip: config.ip,
	routers: [],
  },
  created() {
	this.routes = [];
	if (Array.isArray(this.settings.routes)) {
	  this.settings.routes.forEach(route => this.addRoute(route));
	}
	let driver = this.settings.driver;
	if (this.isHttpServer()) {
	  this.createHttpServer();
	}
	if (this.isUwsServer()) {
	  this.createUwsServer();
	}
	this.logger.info(`Server ${driver} created.`);
  },
  started() {
	/* istanbul ignore next */
	return new this.Promise((resolve, reject) => {
	  // http or http2
	  if (this.isHttpServer()) {
		this.server.listen(this.settings.port, this.settings.ip, err => {
		  if (err) {
			return reject(err);
		  }
		  const addr = this.server.address();
		  this.logger.info(`Server listening on http://${addr.address}:${addr.port}`);
		  resolve();
		});
	  }
	  // uws
	  if (this.isUwsServer()) {
		this.server.listen(this.settings.port, (token) => {
		  if (token) {
			this.logger.info(`Server listening uws on port ${this.settings.port}`);
			resolve();
		  } else {
			reject(err);
		  }
		});
	  }
	  
	});
  },
  stopped() {
	if (this.isUwsServer()) {
	  this.server.forcefully_free();
	  return this.Promise.resolve();
	}
	
	if (this.isHttpServer() && this.server.listening) {
	  /* istanbul ignore next */
	  return new this.Promise((resolve, reject) => {
		this.server.close(err => {
		  if (err) {
			return reject(err);
		  }
		  this.logger.info("Server stopped!");
		  return resolve();
		});
	  });
	}
	
	return this.Promise.resolve();
  },
  
  methods: {
	routeHandler(ctx, route, req, res) {
	  console.log('routeHandler', ctx);
	  res.end('test');
	},
	removeRoute(path) {
	  const idx = this.routes.findIndex(r => r.opts.path == path);
	  if (idx !== -1)
		this.routes.splice(idx, 1);
	},
	addRoute(opts, toBottom = true) {
	  const route = this.createRoute(opts);
	  const idx = this.routes.findIndex(r => r.path == route.path);
	  if (idx !== -1) {
		this.routes[idx] = route;
	  } else {
		if (toBottom) {
		  this.routes.push(route);
		} else {
		  this.routes.unshift(route);
		}
	  }
	  return route;
	},
	createRoute(opts) {
	  let route = {
		opts
	  };
	  // `onBeforeCall` handler
	  if (opts.onBeforeCall)
		route.onBeforeCall = this.Promise.method(opts.onBeforeCall);
	  
	  // `onAfterCall` handler
	  if (opts.onAfterCall)
		route.onAfterCall = this.Promise.method(opts.onAfterCall);
	  
	  // `onError` handler
	  if (opts.onError)
		route.onError = opts.onError;
	  
	  return route;
	},
	
	createHttpServer() {
	  
	  this.server = Http.createServer((req, res) => {
		this.httpHandler(req, res);
	  });
	  
	  this.server.on("error", err => {
		this.logger.error("Server http error", err);
	  });
	},
	
	createUwsServer() {
	  this.server = Uws.App({});
	  this.server.any('/*', async (res, req) => {
		res.onAborted(() => {
		  res.aborted = true;
		});
		await this.httpHandler(req, res);
	  });
	},
	async httpHandler(_req, _res) {
	  // wrap request & response
	  let req = new RequestData(_req, this.settings.driver);
	  let res = new ResponseData(_res, this.settings.driver);
	  
	  return await this.actions.rest({req, res}).then(result => {
	    
	    req._reuest.getCclient();
	    
	    if(result === null){
		  res.end('Router not found');
		}
	  }).catch(err => {
		res.end('ERROR');
	  });
	  
	},
	isHttpServer() {
	  return [DRIVERS.HTTP, DRIVERS.HTTP2].indexOf(this.settings.driver) !== -1;
	},
	isUwsServer() {
	  return this.settings.driver === DRIVERS.UWS;
	},
  }
  
};
```

test service
```js
const WebServer = require('../mixins/web-server');
module.exports = {
    name: 'test-service',
    mixins: [WebServer],
    actions: {
        hello(){},
    },
    routers: [
    
    ],
    created(){
    }
};
```
index.js
```js
const { resolve } = require('path');
const { ServiceBroker } = require('moleculer');

const config = require('./../config/moleculer.config.js');

const broker = new ServiceBroker(config);

broker.loadServices(
    resolve(__dirname, 'services'), '*.service.js',
);

broker.start().then(() => {});
```

**Comment by sanchezzzhak** [comment]
above I attached a project with an error
I think there is a bug in proxying in c++ code between services/mixins
```
MoleculerError: Using uWS.HttpRequest past its request handler return is forbidden (it is stack allocated).
    at handler.catch.err (/srv/www/node-moleculer-web/node_modules/moleculer/src/middlewares/error-handler.js:17:12)
    at tryCatcher (/srv/www/node-moleculer-web/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/srv/www/node-moleculer-web/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/srv/www/node-moleculer-web/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/srv/www/node-moleculer-web/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/srv/www/node-moleculer-web/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/srv/www/node-moleculer-web/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/srv/www/node-moleculer-web/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/srv/www/node-moleculer-web/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/srv/www/node-moleculer-web/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:637:19)
```

**Comment by icebob** [comment]
Could you make a repro repo?

**Comment by sanchezzzhak** [comment]
https://github.com/sanchezzzhak/node-moleculer-web
UWS 
https://github.com/sanchezzzhak/node-moleculer-web/blob/master/src/mixins/web-server.js

**Comment by sanchezzzhak** [comment]
I managed to solve this problem.
```res.end(); - must be called only once and finale```

in my implementation this is not so
