### ISSUE TITLE
Problems encountered when integrating moleculerjs and moleculer-java：Cannot read property 'rest' of undefined

### ISSUE THREAD

**Issue by baozhoutao** [moleculerjs/moleculer-web#302]
This is a great project 👏👏👏

In the [moleculer-spring-boot-demo](https://github.com/moleculer-java/moleculer-spring-boot-demo) project, connect the transporter of the moleculerjs project. Cause the moleculerjs service to hang

```
TypeError: Cannot read property 'rest' of undefined
    at F:\GitHub\steedos-platform\node_modules\moleculer-web\src\index.js:1384:61
    at Array.forEach (<anonymous>)
    at Service.regenerateAutoAliases (F:\GitHub\steedos-platform\node_modules\moleculer-web\src\index.js:1382:13)
    at F:\GitHub\steedos-platform\node_modules\moleculer-web\src\index.js:1474:64
    at Array.forEach (<anonymous>)
    at Service.<anonymous> (F:\GitHub\steedos-platform\node_modules\moleculer-web\src\index.js:1474:16)
    at invokeFunc (F:\GitHub\steedos-platform\node_modules\lodash\lodash.js:10359:23)
    at trailingEdge (F:\GitHub\steedos-platform\node_modules\lodash\lodash.js:10408:18)
    at Timeout.timerExpired [as _onTimeout] (F:\GitHub\steedos-platform\node_modules\lodash\lodash.js:10396:18)
```

![image](https://user-images.githubusercontent.com/6194462/155667421-7f177068-ac8f-47f1-be23-91ce99ac645c.png)

**Comment by baozhoutao** [comment]
service.settings is undefined

**Comment by icebob** [comment]
Please upgrade, this issue is fixed in the latest version:

https://github.com/moleculerjs/moleculer-web/blob/b858f1ee67aa4bd3434ba981d43d2fdf249f4402/src/index.js#L1476
