### ISSUE TITLE
How do I change the maximum size of a request?

### ISSUE THREAD

**Issue by JeStasG** [moleculerjs/moleculer-web#46]
How do I change the maximum size of a request?
Attempt:
`let bodyParser = require("body-parser");`

and in settings: 
``` 
{
...
bodyParser({ json: true, limit: 1024*1024*1 })
...
}
```
Has not given result: Global error: request entity too large.

 Middleware error! { MoleculerError: request entity too large
    at Service.compose.err (\node_modules\moleculer-web\src\index.js:452:24)
    at next (\node_modules\moleculer-web\src\index.js:125:20)
    at mws.(anonymous function).call.err (\moleculer-web\src\index.js:129:41)
    at Array.onfinished (\node_modules\body-parser\lib\read.js:95:9)
    at listener (\node_modules\on-finished\index.js:169:15)
    at onFinish (\node_modules\on-finished\index.js:100:5)
    at callback (\node_modules\ee-first\index.js:55:10)
    at IncomingMessage.onevent (\node_modules\ee-first\index.js:93:5)
    at IncomingMessage.emit (events.js:160:13)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  code: 413,
  type: 'entity.too.large',
  data: undefined,
  retryable: false }
Request - POST, data - JSON.

**Comment by icebob** [comment]
Use the correct syntax](https://github.com/expressjs/body-parser#change-accepted-type-for-parsers): `bodyParser.json({ limit: 1024*1024*1 })`

**Comment by JeStasG** [comment]
Thanks, I managed to solve as follows,
in the router:
`
bodyParsers: {
        json: {
            limit: 1024*1024*1
        }
    }
`

**Comment by wuyuedefeng** [comment]
not work for me.

**Comment by wuyuedefeng** [comment]
`parameters.too.many` add `parameterLimit`
` entity too large` add `limit`

eg: 
```javascript
bodyParsers: {
  json: {
    strict: false,
    limit: '3MB'
  },
  urlencoded: {
    extended: true,
    limit: '3MB',
    parameterLimit: 5000 * 5
  }
}
```

**Comment by chirag-aura** [comment]
@JeStasG is it different for multipart type request? I had already added this for every route. but when I send multipart type request it gives me error of entity too large.
