### ISSUE TITLE
Service not found

### ISSUE THREAD

**Issue by architechcro** [moleculerjs/moleculer-web#58]
I'm using Rest example and trying to add new service - post.service.js

Posts service starts - as seen in the log file
```
[2018-07-06T15:42:32.126Z] DEBUG node-1/BROKER: Broadcast '$services.changed' local event.
[2018-07-06T15:42:32.128Z] DEBUG node-1/BROKER: Load service 'posts.service.js'...
[2018-07-06T15:42:32.134Z] INFO  node-1/REGISTRY: 'posts' service is registered.
[2018-07-06T15:42:32.134Z] DEBUG node-1/POSTS:v1: Created post service
[2018-07-06T15:42:32.135Z] DEBUG node-1/BROKER: Broadcast '$services.changed' local event.
[2018-07-06T15:42:32.136Z] DEBUG node-1/BROKER: Watching 'posts' service file...
[2018-07-06T15:42:32.138Z] DEBUG node-1/POSTS:v1: Post service strted
```

and is seen running

```
mol $ services
╔═════════╤═════════╤══════════╤═════════╤════════╤═══════╗
║ Service │ Version │    State │ Actions │ Events │ Nodes ║
╟─────────┼─────────┼──────────┼─────────┼────────┼───────╢
║ $node   │       - │    OK    │       5 │      0 │ 1     ║
║ api     │       - │    OK    │       1 │      0 │ 1     ║
║ greeter │       - │    OK    │       2 │      0 │ 1     ║
║ posts   │       1 │    OK    │       2 │      0 │ 1     ║
╚═════════╧═════════╧══════════╧═════════╧════════╧═══════╝
```

route alias is configured in api.service.js
`	routes: [
		{
			path: '/posts',
			aliases: {
				"GET posts": "posts.get",
				"health": "$node.health"
			},
...
`

but when I try to 
```
[2018-07-06T15:41:18.874Z] INFO  node-1/API: => GET /api/posts
[2018-07-06T15:41:18.912Z] WARN  node-1/BROKER: Service 'posts' is not registered.
[2018-07-06T15:41:18.928Z] ERROR node-1/API:   Request error! ServiceNotFoundError : Service 'posts' is not found.
 ServiceNotFoundError: Service 'posts' is not found.
    at ServiceBroker.findNextActionEndpoint (D:\dev\moleculertest1\apiservertest\node_modules\moleculer\src\service-broker.js:830:13)
    at p.Promise.resolve.then (D:\dev\moleculertest1\apiservertest\node_modules\moleculer-web\src\index.js:634:29)
    at tryCatcher (D:\dev\moleculertest1\apiservertest\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\dev\moleculertest1\apiservertest\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\dev\moleculertest1\apiservertest\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromiseCtx (D:\dev\moleculertest1\apiservertest\node_modules\bluebird\js\release\promise.js:606:10)
    at Async._drainQueue (D:\dev\moleculertest1\apiservertest\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (D:\dev\moleculertest1\apiservertest\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\dev\moleculertest1\apiservertest\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
Data: { action: 'posts', nodeID: undefined }
[2018-07-06T15:41:18.951Z] INFO  node-1/API: <= 404 GET /api/posts
```

**Comment by icebob** [comment]
Your configuration is not correct. The `path: '/posts'` means, the url is `/posts/posts`. If you want to access it via `/api/posts` change your path to `path: '/api'`.
